### PR TITLE
fix(usefullscreen): change isenabled fullsrceen property

### LINKED ISSUE #410: useFullscreen : isEnabled is not relevant
**Describe the bug**
In the useFullscreen hook, the `isEnabled` property is defined with `Boolean(element)`. But `element` is defined by the document property `fullscreenElement`, which is null if fullscreen is not open.

So `isEnabled` is `false` by default as describe in this documentation : https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide#other_information

**To Reproduce**
install and use @rooks/use-fullscreen as describe in the documentation : https://react-hooks.org/docs/use-fullscreen/

**Expected behavior**
`isEnabled` should be used as a flag to check if fullscreen is allowed / supported

**Desktop (please complete the following information):**
 - all

**Smartphone (please complete the following information):**
 - all

**Additional context**
This issue should be resolved with changing `isEnabled` declaration from `Boolean(element)` to `Boolean(document[fullscreenControls.fullscreenEnabled])`

### PR DESCRIPTION
**Pull request by thodubois**
Change property `isEnabled` to match mdn documentation.
fix #410

### CODE REVIEW

File: packages/shared/useFullscreen.ts [hunk 1]
```diff
@@ -206,7 +206,7 @@ function useFullscreen(
   );
 
   return {
-    isEnabled: Boolean(element),
+    isEnabled: Boolean(document[fullscreenControls.fullscreenEnabled]),
```
Comment (imbhargav5) [inline packages/shared/useFullscreen.ts:209]: Is there a merit to doing this over the existing `element` variable? 🤔 

cc @simbathesailor

Comment (thodubois) [reply packages/shared/useFullscreen.ts:209]: Yes, as it is describe here : https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#properties 

The element only tells you if fullscreen mode is activated (as `isFullscreen` is meant to)
```
Document.fullscreenElement / ShadowRoot.fullscreenElement
    The fullscreenElement property tells you the Element that's currently being displayed in full-screen mode on the DOM (or shadow DOM). If this is null, the document (or shadow DOM) is not in full-screen mode.
```

`fullscreenEnabled` tells you if fullscreen is supported or not
```
document.fullscreenEnabled
    The fullscreenEnabled property tells you whether or not it is possible to engage full-screen mode. This is false if full-screen mode is not available for any reason (such as the "fullscreen" feature not being allowed, or full-screen mode not being supported).
```

Comment (simbathesailor) [reply packages/shared/useFullscreen.ts:209]: Yes I agree with thodubois , document.fullscreenEnabled should be used instead of Document.fullscreenElement /  ShadowRoot.fullscreenElement. That's what I can understand from docs

Comment (thodubois) [reply packages/shared/useFullscreen.ts:209]: It seems it was like this before:
https://github.com/imbhargav5/rooks/blob/0180335c454c035c586246df10c7d9ad12f0275b/packages/shared/useFullscreen.ts#L150

Comment (imbhargav5) [reply packages/shared/useFullscreen.ts:209]: Sounds good!

**Comment by imbhargav5** [comment]
@all-contributors please add @thodubois for code.
